{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-ingress-dash.serviceAccountName" . }}
  labels:
    {{- include "kube-ingress-dash.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-ingress-dash.fullname" . }}-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "services", "pods"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-ingress-dash.fullname" . }}-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-ingress-dash.fullname" . }}-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ include "kube-ingress-dash.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}