apiVersion: v2
name: kube-ingress-dash
description: A Kubernetes Ingress Dashboard
type: application
version: 0.2.4
appVersion: "0.2.4"
keywords:
  - kubernetes
  - ingress
  - dashboard
  - monitoring
  - visualization
home: https://github.com/wasilak/kube-ingress-dash
icon: https://github.com/wasilak/kube-ingress-dash/raw/main/docs-site/static/img/logo.svg
sources:
  - https://github.com/wasilak/kube-ingress-dash
maintainers:
  - name: Piotr Boruc
    email: piotr.m.boruc@gmail.com
