name: Helm Chart

on:
  push:
    tags:
      - "v*.*.*"
      - "!v*-docs" # Exclude documentation tags
  workflow_dispatch:

env:
  HELM_REGISTRY: ghcr.io
  HELM_NAMESPACE: ${{ github.repository_owner }}

jobs:
  publish-helm-chart:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Log into Helm registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.HELM_REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Package and push Helm chart to OCI registry
        env:
          CHART_NAME: ${{ github.event.repository.name }}
        run: |
          cd charts
          VERSION=${GITHUB_REF_NAME#v}
          CHART_PACKAGE_NAME=${CHART_NAME}-chart
          # Update version in Chart.yaml temporarily for this build
          sed -i "s/version: .*/version: $VERSION/" $CHART_NAME/Chart.yaml
          sed -i "s/appVersion: .*/appVersion: \"$VERSION\"/" $CHART_NAME/Chart.yaml
          # Package the chartdocker pull ghcr.io/wasilak/kube-ingress-dash:latest
          helm package $CHART_NAME/ --destination .
          # Rename the chart package to avoid collision
          mv $CHART_NAME-$VERSION.tgz $CHART_PACKAGE_NAME-$VERSION.tgz
          # Push to OCI registry under unique chart path
          helm push $CHART_PACKAGE_NAME-$VERSION.tgz oci://${{ env.HELM_REGISTRY }}/${{ env.HELM_NAMESPACE }}/$CHART_PACKAGE_NAME
